# TODO: Switch to stable Rust when we don't use nightly features anymore.

name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install nasm

    - name: Setup Rust
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustup component add clippy

    - name: Compile
      run: |
        cd tiger
        cargo build

    - name: Test
      run: |
        cd tiger
        cargo test

    - name: Clippy
      run: |
        cd tiger
        cargo clippy --all-targets -- -D warnings
